---
# tasks file for dnsmasq

- name: Install dnsmasq
  become: true
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Create TFTP directory
  become: true
  ansible.builtin.file:
    path: '{{tftp_root}}'
    state: directory

- name: Setup dnsmasq ProxyDHCP configuration
  become: true
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 644

- name: Install iPXE binaries for TFTP server
  become: true
  ansible.builtin.get_url:
    url: '{{ item }}'
    dest: '{{ tftp_root }}'
    mode: '0400'
    owner: dnsmasq
    group: dnsmasq
  with_items:
    - '{{ ipxe_binaries }}'

- name: Enable dnsmasq service
  become: true
  ansible.builtin.service:
    name: dnsmasq
    enabled: yes
    state: reloaded
