---
# tasks file for dnsmasq

- name: Install dnsmasq
  become: true
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Create TFTP directory
  become: true
  ansible.builtin.file:
    path: '{{tftp_root}}'
    state: directory

- name: Setup dnsmasq ProxyDHCP configuration
  become: true
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 644
