---
- name: "Setup the public key authentication"
  authorized_key:
    state: present
    user: "{{ ansible_first_login_user }}"
    key: "{{ lookup('file', playbook_dir + '/' + ansible_ssh_private_key_file) }}"
